import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'




export default function Home({ user }) {
  console.log(user);
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Anasayfa</h3>
      <h1>{user.email}</h1>
    </>

  )
}

export async function getStaticProps() {

  const request = await fetch("https://randomuser.me/api/")
  const response = await request.json()

  return {
    props: {
      user: response.results[0]
    }
  }
}
